// <auto-generated />
using System;
using ImmoDigger.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ImmoDigger.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ImmoDiggerDbContext))]
    partial class ImmoDiggerDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ImmoDigger.Domain.Entities.ListingPriceHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Price")
                        .HasPrecision(14, 2)
                        .HasColumnType("numeric(14,2)");

                    b.Property<Guid>("PropertyListingId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("RecordedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("PropertyListingId", "RecordedAt");

                    b.ToTable("ListingPriceHistories", (string)null);
                });

            modelBuilder.Entity("ImmoDigger.Domain.Entities.ListingSource", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Allowed")
                        .HasColumnType("boolean");

                    b.Property<string>("BaseUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("CollectionMethod")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("LastError")
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastFailedRunAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LastSuccessfulRunAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<int>("PollingIntervalMinutes")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("RobotsCheckedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("TermsCheckedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("ListingSources", (string)null);
                });

            modelBuilder.Entity("ImmoDigger.Domain.Entities.NotificationHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Error")
                        .HasColumnType("text");

                    b.Property<Guid>("PropertyListingId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("PropertyListingId", "Channel");

                    b.ToTable("NotificationHistories", (string)null);
                });

            modelBuilder.Entity("ImmoDigger.Domain.Entities.ProcessedEmailMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("EmailMessageId")
                        .IsRequired()
                        .HasMaxLength(998)
                        .HasColumnType("character varying(998)");

                    b.Property<int>("ListingsExtractedCount")
                        .HasColumnType("integer");

                    b.Property<DateTime>("ProcessedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Sender")
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<string>("Subject")
                        .HasMaxLength(998)
                        .HasColumnType("character varying(998)");

                    b.HasKey("Id");

                    b.HasIndex("EmailMessageId")
                        .IsUnique();

                    b.ToTable("ProcessedEmailMessages", (string)null);
                });

            modelBuilder.Entity("ImmoDigger.Domain.Entities.PropertyListing", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<decimal?>("AskingPrice")
                        .HasPrecision(14, 2)
                        .HasColumnType("numeric(14,2)");

                    b.Property<DateTime?>("AuctionEndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("AuctionStartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("BathroomCount")
                        .HasColumnType("integer");

                    b.Property<int?>("BedroomCount")
                        .HasColumnType("integer");

                    b.Property<decimal?>("CadastralIncome")
                        .HasPrecision(14, 2)
                        .HasColumnType("numeric(14,2)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<decimal?>("CurrentBid")
                        .HasPrecision(14, 2)
                        .HasColumnType("numeric(14,2)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool?>("ElectricalInstallationCompliant")
                        .HasColumnType("boolean");

                    b.Property<string>("EmailMessageId")
                        .HasMaxLength(998)
                        .HasColumnType("character varying(998)");

                    b.Property<string>("EmailSender")
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<string>("EmailSubject")
                        .HasMaxLength(998)
                        .HasColumnType("character varying(998)");

                    b.Property<decimal?>("EstimatedAcquisitionCosts")
                        .HasPrecision(14, 2)
                        .HasColumnType("numeric(14,2)");

                    b.Property<decimal?>("EstimatedFinalPrice")
                        .HasPrecision(14, 2)
                        .HasColumnType("numeric(14,2)");

                    b.Property<decimal?>("EstimatedGrossYield")
                        .HasPrecision(6, 3)
                        .HasColumnType("numeric(6,3)");

                    b.Property<decimal?>("EstimatedMonthlyRentPerUnit")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<decimal?>("EstimatedRenovationBudget")
                        .HasPrecision(14, 2)
                        .HasColumnType("numeric(14,2)");

                    b.Property<decimal?>("EstimatedRenovationCost")
                        .HasPrecision(14, 2)
                        .HasColumnType("numeric(14,2)");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("FirstSeenAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool?>("HasGarage")
                        .HasColumnType("boolean");

                    b.Property<bool?>("HasGarden")
                        .HasColumnType("boolean");

                    b.Property<bool?>("HasTerrace")
                        .HasColumnType("boolean");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool?>("IsOccupied")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsReviewed")
                        .HasColumnType("boolean");

                    b.Property<decimal?>("LandArea")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<DateTime>("LastSeenAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("LivingArea")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<int?>("ObservedUnitCount")
                        .HasColumnType("integer");

                    b.Property<string>("OfficialDocumentsJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("[]");

                    b.Property<int?>("OfficialUnitCount")
                        .HasColumnType("integer");

                    b.Property<string>("OfficialUnitCountSourceName")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("OfficialUnitCountSourceUrl")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<decimal?>("OpportunityScore")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<decimal?>("PebConsumption")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<string>("PebRating")
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)");

                    b.Property<string>("PersonalNotes")
                        .HasColumnType("text");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("PropertyType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("PublishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RawContentHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RiskLevel")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("RiskSummary")
                        .HasColumnType("text");

                    b.Property<string>("SaleType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("UrbanisticStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("Unknown");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.HasKey("Id");

                    b.HasIndex("City");

                    b.HasIndex("FirstSeenAt");

                    b.HasIndex("IsActive");

                    b.HasIndex("OpportunityScore");

                    b.HasIndex("PostalCode");

                    b.HasIndex("UrbanisticStatus");

                    b.HasIndex("Url");

                    b.HasIndex("Source", "ExternalId");

                    b.ToTable("PropertyListings", (string)null);
                });

            modelBuilder.Entity("ImmoDigger.Domain.Entities.SearchProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("IncludePublicSales")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean");

                    b.Property<decimal?>("MaximumPrice")
                        .HasPrecision(14, 2)
                        .HasColumnType("numeric(14,2)");

                    b.Property<decimal?>("MinimumGrossYield")
                        .HasPrecision(6, 3)
                        .HasColumnType("numeric(6,3)");

                    b.Property<decimal?>("MinimumLivingArea")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<decimal?>("MinimumOpportunityScore")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<int?>("MinimumUnitCount")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.PrimitiveCollection<string[]>("PostalCodes")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.PrimitiveCollection<string[]>("PropertyTypes")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<bool>("RequireGarage")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("SearchProfiles", (string)null);
                });

            modelBuilder.Entity("ImmoDigger.Domain.Entities.ListingPriceHistory", b =>
                {
                    b.HasOne("ImmoDigger.Domain.Entities.PropertyListing", "PropertyListing")
                        .WithMany("PriceHistory")
                        .HasForeignKey("PropertyListingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PropertyListing");
                });

            modelBuilder.Entity("ImmoDigger.Domain.Entities.NotificationHistory", b =>
                {
                    b.HasOne("ImmoDigger.Domain.Entities.PropertyListing", "PropertyListing")
                        .WithMany("Notifications")
                        .HasForeignKey("PropertyListingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PropertyListing");
                });

            modelBuilder.Entity("ImmoDigger.Domain.Entities.PropertyListing", b =>
                {
                    b.Navigation("Notifications");

                    b.Navigation("PriceHistory");
                });
#pragma warning restore 612, 618
        }
    }
}
