namespace ImmoDigger.Application.DTOs;

/// <summary>Shape used by the listings list/grid view (<c>GET /api/listings</c>).</summary>
public sealed record ListingSummaryDto(
    Guid Id,
    string Source,
    string Title,
    string Url,
    string? ImageUrl,
    string Description,
    string Address,
    string City,
    string PostalCode,
    decimal? AskingPrice,
    decimal? CurrentBid,
    int? UnitCount,
    int? BedroomCount,
    int? BathroomCount,
    int OfficialDocumentCount,
    decimal? LivingArea,
    decimal? LandArea,
    string? PebRating,
    decimal? EstimatedGrossYield,
    decimal? OpportunityScore,
    string? RiskLevel,
    string? RiskSummary,
    string SaleType,
    string PropertyType,
    bool IsActive,
    bool IsDemo,
    bool IsReviewed,
    DateTime FirstSeenAt,
    string UrbanisticStatus,
    DateTime ListedSince,
    int? IndexCriteriaCount);
